baseURL = "https://kkundu10.github.io"

# set your your own ga token here.
googleAnalytics = ""

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Kaustav Kundu"

# number of posts to show on the blog page
paginate = 10

[markup]
[markup.tableOfContents]
endLevel = 8
ordered = false
startLevel = 1

[params]
# it is used for the copy-right section of your page
name = "Kaustav Kundu"
